version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pagamento_app
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - db
    environment:
      - AWS_REGION="$${{ secrets.AWS_REGION }}"
      - AWS_ACCESS_KEY="$${{ secrets.AWS_ACCESS_KEY }}"
      - AWS_SECRET_KEY="$${{ secrets.AWS_SECRET_KEY }}"
      - AWS_DYNAMODB_ENDPOINT="$${{ secrets.AWS_DYNAMODB_ENDPOINT }}"

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=dynamodb
      - LOCALSTACK_HOST=localstack:4566
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./localstack:/etc/localstack/init/ready.d:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
