apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pagamento
  labels:
    name: ms-pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pagamento
  template:
    metadata:
      labels:
        app: ms-pagamento
    spec:
      containers:
      - name: ms-pagamento
        image: olegon/soat1-grupo18-ms-pagamento:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "2000m"
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: aws_region
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_key
        - name: AWS_DYNAMODB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: aws_dynamodb_endpoint
        - name: AWS_SQS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: aws_sqs_endpoint
        - name: AWS_SNS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: aws_sns_endpoint
        ports:
        - containerPort: 8080
